version: '3'
services:
  dev-db:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate
    networks:
      - workspace
  test-db:
    image: postgres
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate
    networks:
      - workspace
networks:
  workspace: