version: '3'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: activities
    networks:
      - workspace

networks:
  workspace: