version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    # volumes:
    #   - ./dockers/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: boilerplate
    ports:
      - 5434:5432
      - 5432:5432
    networks:
      - workspace
  # mariadb:
  #   image: mariadb:10.9
  #   container_name: mariadb
  #   restart: always
  #   ports:
  #     - 3306:3306
  #   # volumes:
  #   #   - ./dockers/mariadb:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root

networks:
  workspace:
